<!DOCTYPE html>
<html>
  <head>
    <title>Filehosting &mdash; Last files</title>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li class="active">
            <a href="/">Главная</a>
          </li>
          <li>
            <a href="/last/">Последние файлы</a>
          </li>
        </ul>
      </div>
    </nav>
